<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://exercise3.wdsr/hr/definitions" xmlns:schema="http://exercise3.wdsr/hr/schemas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://exercise3.wdsr/hr/definitions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:types>
<xsd:schema xmlns:schema="http://exercise3.wdsr/hr/schemas" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://exercise3.wdsr/hr/definitions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:import schemaLocation="http://localhost:8090/holidayService/?xsd=hr.xsd" namespace="http://exercise3.wdsr/hr/schemas"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="HolidayResponse">
<wsdl:part name="HolidayResponse" element="schema:HolidayResponse"> </wsdl:part>
</wsdl:message>
<wsdl:message name="HolidayRequest">
<wsdl:part name="HolidayRequest" element="schema:HolidayRequest"> </wsdl:part>
</wsdl:message>
<wsdl:portType name="HumanResource">
<wsdl:operation name="Holiday">
<wsdl:input name="HolidayRequest" message="tns:HolidayRequest"> </wsdl:input>
<wsdl:output name="HolidayResponse" message="tns:HolidayResponse"> </wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="HumanResourceBinding" type="tns:HumanResource">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<wsdl:operation name="Holiday">
<soap:operation soapAction="http://exercise3.wdsr/RequestHoliday"/>
<wsdl:input name="HolidayRequest">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="HolidayResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="HumanResourceService">
<wsdl:port name="HumanResourcePort" binding="tns:HumanResourceBinding">
<soap:address location="http://localhost:8090/holidayService/"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>