package wdsr.exercise3.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-03T15:50:17.160+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://exercise3.wdsr/hr/definitions", name = "HumanResource")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface HumanResource {

    @WebMethod(operationName = "Holiday", action = "http://exercise3.wdsr/RequestHoliday")
    @WebResult(name = "HolidayResponse", targetNamespace = "http://exercise3.wdsr/hr/schemas", partName = "HolidayResponse")
    public HolidayResponse holiday(
        @WebParam(partName = "HolidayRequest", name = "HolidayRequest", targetNamespace = "http://exercise3.wdsr/hr/schemas")
        HolidayRequest holidayRequest
    );
}
