
package wdsr.exercise3.hr;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import wdsr.exercise3.hr.ws.HolidayRequest;
import wdsr.exercise3.hr.ws.HumanResource;
import wdsr.exercise3.hr.ws.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-18T12:12:35.237+01:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "HumanResourceService",
                      portName = "HumanResourcePort",
                      targetNamespace = "http://exercise3.wdsr/hr/definitions",
                      wsdlLocation = "classpath:/hr.wsdl",
                      endpointInterface = "wdsr.exercise3.hr.ws.HumanResource")
                      
public class HumanResourcePortImpl implements HumanResource {
    private static final Logger LOG = Logger.getLogger(HumanResourcePortImpl.class.getName());
    
    private HolidayRepository repo;
    
    public HumanResourcePortImpl(HolidayRepository repo) {
    	this.repo = repo;
    }

    /* (non-Javadoc)
     * @see wdsr.exercise3.hr.HumanResource#holiday(wdsr.exercise3.hr.HolidayRequest  holidayRequest )*
     */
    public wdsr.exercise3.hr.ws.HolidayResponse holiday(HolidayRequest holidayRequest) { 
        LOG.log(Level.INFO, "Executing operation holiday [holidayRequest={0}]", holidayRequest);
        int employeeId = holidayRequest.getEmployee().getNumber();
        Date fromDate = holidayRequest.getHoliday().getStartDate();
        Date endDate = holidayRequest.getHoliday().getEndDate();
        int requestId = repo.saveHolidayRequest(employeeId, fromDate, endDate);
        wdsr.exercise3.hr.ws.HolidayResponse _return = new ObjectFactory().createHolidayResponse();
        _return.setRequestId(requestId);
        LOG.log(Level.INFO, "Returning result of operation holiday [_return={0}]", _return);
        return _return;
    }
}
